# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/jordis_db
spring.datasource.username=jordis_user
spring.datasource.password=jordis2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialización SQL manual
spring.sql.init.mode=never

spring.main.web-application-type=none

# Logging
logging.level.com.jordis=DEBUG
logging.level.org.hibernate.SQL=DEBUG